<div class="col-md-12" style="height: 10px;">&nbsp;</div>

<div style="clear: both;"></div>

<div class="col-md-12">
    <div class="col-xs-10"></div>
    <div class="col-xs-1"></div>
</div>

<div class="col-md-12" >
    <div class="col-md-3 col-xs-4">
    
        <?php
        
        if($this->imgGrupo != ''):
            ?>
            <img src="<?php echo $this->imgGrupo; ?>" class="img-responsive" />
            <?php
        else:
            ?>
            <img src="http://placehold.it/350x150" class="img-responsive" />
            <?php
        endif;
        ?>
    </div>
    
    <div class="col-md-7 col-xs-8" style="font-size: 20px;">

        <?php
        
        echo "<b>Artist:</b> ". $this->artist."<br/>";
        echo "<b>Album:</b> ". $this->albumName."<br/>";
        echo "<b>Cancion:</b> ". $this->song."<br/>";
        
        ?>
    </div>
    
    <div class="col-md-2">
        <form id="enviarSentimiento" action="<?php BASE_URL; ?>" method="post">
            <input type="hidden" name="generar" value="1" />
            <input type="hidden" name="speed" value="<?php echo $this->speed; ?>" />
        </form>
        
        <img  src="<?php echo $_layoutParams['ruta_img']; ?>flecha_der.png" class="img-responsive" style="cursor:  pointer;" onclick="_('enviarSentimiento').submit();"></div>
    </div>
</div>

<div class="col-md-12" style="margin-top: 35px;">

    <div class="col-md-12">
        <div class="row">
            <div class="text-center" style="width: 40px; height: 40px; background: #c5432e;">
                <img id="btnRepro" src="<?php echo $_layoutParams['ruta_img']; ?>pause.png" style="margin-top: 5px;" onclick="pauseTeme();">
            </div>
        </div>
    </div>
    
    <div id="reproductor" class="col-md-12" style="background: #fff; height: 20px; overflow: hidden;">
        <div class="row">
            <div id="estado" style="width: 0; background: #c5432e; height: 20px;">
            
            </div>
        </div>
    </div>
</div>